# Generated by Django 5.0.4 on 2024-04-30 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0007_alter_rating_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='menuitem_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_app.menu'),
        ),
    ]
