# Generated by Django 5.0.4 on 2024-05-01 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0008_alter_rating_menuitem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('inventory', models.SmallIntegerField()),
                ('description', models.CharField(default='', max_length=1000)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='restaurant_app.category')),
            ],
        ),
        migrations.AlterField(
            model_name='rating',
            name='menuitem_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_app.menuitem'),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
